import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Eye, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { accountsApi } from '../api/accountsApi'
import { PageHeader } from '../components/ui/PageHeader'
import { EmptyState, PageLoading } from '../components/ui/States'
import type { AccountResponse, AccountType } from '../types/api'
import { formatCurrency } from '../utils/currency'
import { formatDateTime } from '../utils/dates'
import { getErrorMessage } from '../utils/errors'

export function AccountsPage() {
  const [accounts, setAccounts] = useState<AccountResponse[] | null>(null); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [type, setType] = useState<AccountType | 'ALL'>('ALL'); const [threshold, setThreshold] = useState(''); const [premiumActive, setPremiumActive] = useState(false)
  const load = useCallback(async () => { setError(''); try { setAccounts(await accountsApi.list()); setPremiumActive(false) } catch (cause) { setError(getErrorMessage(cause)) } }, [])
  useEffect(() => { void load() }, [load])
  async function premium(event: FormEvent) { event.preventDefault(); const value = Number(threshold); if (threshold === '' || value < 0 || !/^\d+(\.\d{1,2})?$/.test(threshold)) { setError('Enter a non-negative threshold with no more than 2 decimal places.'); return } setError(''); try { setAccounts(await accountsApi.premium(value)); setPremiumActive(true) } catch (cause) { setError(getErrorMessage(cause)) } }
  const filtered = useMemo(() => (accounts || []).filter((account) => (type === 'ALL' || account.accountType === type) && `${account.accountId} ${account.userName}`.toLowerCase().includes(query.toLowerCase())), [accounts, type, query])
  if (!accounts && !error) return <PageLoading />
  return <><PageHeader eyebrow="Account directory" title="Accounts" description="Review balances, ownership, and account status." actions={<Link className="button" to="/accounts/new"><Plus size={17} />Open account</Link>} />{error && <div className="inline-notice inline-notice--error" role="alert">{error}</div>}<section className="panel"><div className="toolbar toolbar--wrap"><label className="search-field"><Search size={17} /><span className="sr-only">Search accounts</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customer or account ID" /></label><label className="compact-field"><span className="sr-only">Filter account type</span><select value={type} onChange={(e) => setType(e.target.value as AccountType | 'ALL')}><option value="ALL">All types</option><option value="CHECKING">Checking</option><option value="SAVINGS">Savings</option></select></label><form className="premium-filter" onSubmit={premium}><SlidersHorizontal size={16} /><label><span className="sr-only">Premium balance threshold</span><input inputMode="decimal" value={threshold} onChange={(e) => setThreshold(e.target.value)} placeholder="Minimum balance" /></label><button className="button button--secondary button--small">Apply</button>{premiumActive && <button className="link-button" type="button" onClick={() => { setThreshold(''); void load() }}>Clear</button>}</form></div>{accounts && accounts.length === 0 ? <EmptyState title={premiumActive ? 'No premium accounts' : 'No accounts yet'} message={premiumActive ? 'No account meets this backend balance threshold.' : 'Open an account for a new or existing customer.'} action={!premiumActive && <Link className="button" to="/accounts/new">Open account</Link>} /> : filtered.length === 0 ? <EmptyState title="No matching accounts" message="Adjust the search or account type filter." /> : <div className="table-wrap"><table><thead><tr><th>Account</th><th>Customer</th><th>Type</th><th className="money-cell">Balance</th><th>Opened</th><th className="actions-cell">Actions</th></tr></thead><tbody>{filtered.map((account) => <tr key={account.accountId}><td className="mono">{account.accountId}</td><td><strong>{account.userName}</strong></td><td><span className="badge">{account.accountType}</span></td><td className="money-cell">{formatCurrency(Number(account.balance))}</td><td>{formatDateTime(account.createdAt)}</td><td className="actions-cell"><Link className="icon-button" to={`/accounts/${account.accountId}`} aria-label={`View account ${account.accountId}`} title="View"><Eye size={17} /></Link></td></tr>)}</tbody></table></div>}</section></>
}
