package com.josvier.simplebank.security.authorization;

public enum BankPermission {
    CUSTOMER_SELF_READ,
    CUSTOMER_ANY_READ,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE_SELF,
    CUSTOMER_UPDATE_ANY,
    CUSTOMER_DELETE,
    ACCOUNT_SELF_READ,
    ACCOUNT_ANY_READ,
    ACCOUNT_CREATE,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,
    TRANSACTION_SELF_READ,
    TRANSACTION_ANY_READ,
    DEPOSIT_EXECUTE,
    WITHDRAW_EXECUTE,
    TRANSFER_SELF,
    TRANSFER_ANY,
    PREMIUM_ACCOUNT_READ,
    AUDIT_READ,
    AUTH_MANAGE
}
